name: BuildFlow
# BuildFlow runs on all branches
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.13'
      - run: npm install
      - name: build
        run: npm run build
      - name: build
        run: npm run test
      - name: lint
        run: ng lint

