name: BuildFlow
# BuildFlow runs on all branches
# Contains build, test, integration and lint
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.13'
      - run: npm install
      - run: npm run build
      - run: npm run test
      - run: npm run integration
      - run: ng lint
      - name: Sonar
      - run: sonar-scanner -Dproject.settings=./sonar-project.properties

